name: Auto Renew HidenCloud

on:
  workflow_dispatch:
  schedule:
    - cron: '22 3 * * 4' # 根据到期时间的前一天推算星期几来续期，最后一个数字代表星期

permissions:
  contents: write
  actions: write

jobs:
  renew-hiden:
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true


      - name: ⚙ 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: 🛠️ 安装系统依赖和python依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          pip install patchright requests 'requests[socks]'
          python -m patchright install --with-deps chrome

      - name: ⚙ 设置sing-box代理
        continue-on-error: true
        env:
          NODE_LINK: ${{ secrets.NODE_LINK }}
        run: |
          bash <(wget -qO- https://main.ssss.nyc.mn/setup_proxy.sh)

      - name: 🚀 运行续期脚本
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COOKIE_VALUE: ${{ secrets.COOKIE_VALUE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python -u app.py

      # 更新时间到time.txt,避免6个月未更新导致工作流暂停
      - name: 🕒 更新时间
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" > time.txt
          git add time.txt
          if git diff --cached --quiet; then
            echo "No need to commit"
          else
            git commit -m "⏱️ Auto Update by Github Actions $(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
      
      - name: 🧹 清理旧的工作流运行记录
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          runs=$(gh run list --workflow="${{ github.workflow }}" --limit=100 --json databaseId --jq '.[].databaseId')
          count=0
          for run_id in $runs; do
            count=$((count + 1))
            if [ $count -gt 1 ]; then
              echo "删除运行记录: $run_id"
              gh run delete $run_id || true
            fi
          done
